/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.domainmodel.ide;

import org.xtext.example.domainmodel.ide.AbstractDomainmodelIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DomainmodelIdeModule extends AbstractDomainmodelIdeModule {
}
