/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.domainmodel.ui.tests;

import com.capstone.mydsl.ui.internal.MydslActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class DomainmodelUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MydslActivator.getInstance().getInjector("org.xtext.example.domainmodel.Domainmodel");
	}

}
