/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.domainmodel;

import org.xtext.example.domainmodel.AbstractDomainmodelRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DomainmodelRuntimeModule extends AbstractDomainmodelRuntimeModule {
}
