/*
 * generated by Xtext 2.11.0
 */
package org.xtext.example.domainmodel.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDomainmodelScopeProvider extends DelegatingScopeProvider {
}
