/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.domainmodel.ui;

import com.capstone.mydsl.ui.internal.MydslActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DomainmodelExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MydslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MydslActivator.getInstance().getInjector(MydslActivator.ORG_XTEXT_EXAMPLE_DOMAINMODEL_DOMAINMODEL);
	}
	
}
